// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from "storyblok";
export interface HtmlEmbedProps {
  snippet: string;
  component: "htmlEmbed";
  _uid: string;
  [k: string]: any;
}

export interface MetaProps {
  description?: string;
  component: "meta";
  _uid: string;
  [k: string]: any;
}

export interface PageProps {
  body: (
    | HtmlEmbedProps
    | MetaProps
    | PageProps
    | PageIntroProps
    | PageSectionProps
    | PostProps
    | ProjectCardProps
    | ProjectCardsProps
    | RichTextProps
    | SizeContainerProps
  )[];
  component: "page";
  _uid: string;
  [k: string]: any;
}

export interface RichtextProps {
  type: string;
  content?: RichtextProps[];
  marks?: RichtextProps[];
  attrs?: any;
  text?: string;
  [k: string]: any;
}

export interface PageIntroProps {
  title?: string;
  content?: RichtextProps;
  component: "pageIntro";
  _uid: string;
  [k: string]: any;
}

export interface PageSectionProps {
  blocks: (
    | HtmlEmbedProps
    | MetaProps
    | PageProps
    | PageIntroProps
    | PageSectionProps
    | PostProps
    | ProjectCardProps
    | ProjectCardsProps
    | RichTextProps
    | SizeContainerProps
  )[];
  component: "PageSection";
  _uid: string;
  [k: string]: any;
}

export interface AssetProps {
  alt?: string;
  copyright?: string;
  id: number;
  filename: string;
  name: string;
  title?: string;
  focus?: string;
  [k: string]: any;
}

export interface PostProps {
  body: (
    | HtmlEmbedProps
    | MetaProps
    | PageProps
    | PageIntroProps
    | PageSectionProps
    | PostProps
    | ProjectCardProps
    | ProjectCardsProps
    | RichTextProps
    | SizeContainerProps
  )[];
  metadata?: any;
  description?: string;
  previewImage?: AssetProps;
  component: "post";
  _uid: string;
  [k: string]: any;
}

export interface ProjectCardProps {
  name: string;
  url: string;
  date: string;
  role: string;
  description: RichtextProps;
  screenshot: AssetProps;
  component: "projectCard";
  _uid: string;
  [k: string]: any;
}

export interface ProjectCardsProps {
  projects: ProjectCardProps[];
  component: "projectCards";
  _uid: string;
  [k: string]: any;
}

export interface RichTextProps {
  content: RichtextProps;
  component: "richText";
  _uid: string;
  [k: string]: any;
}

export interface SizeContainerProps {
  size: "250" | "300" | "";
  children?: (
    | HtmlEmbedProps
    | MetaProps
    | PageProps
    | PageIntroProps
    | PageSectionProps
    | PostProps
    | ProjectCardProps
    | ProjectCardsProps
    | RichTextProps
    | SizeContainerProps
  )[];
  component: "sizeContainer";
  _uid: string;
  [k: string]: any;
}
